@startuml structure

package "script" {
  main - [récupération data] 
  main - [communication avec IA]
  main - [interpretation resultat model ia ]
}

node "data" {
  [mp3]
  [wav]
}


database "Sql" {
  folder "voice" {
    [dabse de doonée]
  }

}

database "Sql2" {
  folder "resultat" {
    [dabse de doonée2]
  }

}

node "data2" {
  [json2]
  [csv2]
}

node "model IA" {
}

[récupération data] <--* [provider1]
[provider1] <-- data
[provider1] <-- Sql
[provider1] <-- user_input
[communication avec IA] <--* "model IA"

[interpretation resultat model ia ] <--* [provider2] 
[provider2] <-- data2
[provider2] <-- Sql2

@endumltest